mysql:
  host: "localhost"
  name: "hyper"
  password: "bXkn868bWDaLXJ3m"
  database: "hyper"

messgae:
  PREFIX: "§x§f§b§2§2§e§5§l[§x§e§c§2§b§e§7§lH§x§d§c§3§3§e§9§ly§x§c§d§3§c§e§c§lp§x§b§e§4§5§e§e§le§x§a§e§4§e§f§0§lr§x§9§f§5§6§f§2§lS§x§8§f§5§f§f§4§lt§x§8§0§6§8§f§6§la§x§7§1§7§1§f§9§ln§x§6§1§7§9§f§b§ld§x§5§2§8§2§f§d§l]"
  COMMAND_NO_PERMISSIONS: "{prefix} §cDazu hast du keine Rechte!"
  COMMAND_DEFAULT_USAGE: "{prefix} §7Benutze §c/hyperstand help §7für eine Liste aller Befehle"
  COMMAND_SAVE_USAGE: "{prefix} §cBenutze /hyperstand save <Name> <Beschreibung>"
  COMMAND_CREATE_ITEM_GIVEN: "{prefix} §aDu hast einen HyperStand erhalten!"
  NEED_TO_LOOK_AT_ARMOR_STAND: "{prefix} §cDu musst einen ArmorStand anschauen!"
  HYPERSTAND_ALREADY_IN_USE: "{prefix} §cDer ArmorStand wird bereits von jemand andern Bearbeitet!"
  HYPERSTAND_NOT_EDIBLE: "{prefix} §cDer ArmorStand kann nicht bearbeitet werden!"
  HYPERSTAND_NO_ACCESS: "{prefix} §cDu kannst den ArmorStand nicht bearbeiten!"
  HYPERSTAND_ALLRADY_EXIST: "{prefix} §cDas ist bereits ein HyperStand"
  HYPERSTAND_CREATED: "{prefix} §aDu hast den HyperStand erstellt!"
  MYSQL_ERROR: "{prefix} §cLeider ist ein Fehler aufgetreten.!"
  create_template: "{prefix} §7Die Position wird gespeichert..."
  create_template_success: "{prefix} §aDie Position §a§l{0} §awurde erfolgreich gespeichert!"
  create_template_max: "§{prefix} cDu hast bereits 14 Positionen gespeichert!"
  create_template_exist: "{prefix} §cDer Name ist bereits vergeben"
  CANT_PLACE_HERE: "{prefix} §cDu kannst den HyperStand hier nicht platzieren!"
  USE_HYPERSTAND: "{prefix} §7Dises Item kann nicht platziert werden!"
  HOW_TO_USE_HYPERSTAND: "{prefix} §7Du musst auf einen Rüstungsständer klicken!"
  HYPSERSTAND_SET_NAME: "{prefix} §7Benutze hierfür §c/hyperstand name§7!"
  NAME_TO_LONG: "{prefix} §cDer Name ist zu lang! Maximal 30 Zeichen!"
  NAME_SET: "{prefix} §aDer Name wurde erfolgreich auf {0} §agesetzt!"